# Generated by Django 3.1.7 on 2021-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='author',
            new_name='gamer',
        ),
    ]
